import { Grid, Title, Text, Container, Space, Table, Card, Button, Anchor } from "@mantine/core"
import Image from "next/image";
import { useEffect, useState } from "react";
import initSdk from "../initSDK";
import connectContract from "../connectContract";
import ABI from "../ABI.json";
import { utils } from 'ethers';
import { IconArrowUpRight } from "@tabler/icons-react";

export default function Home() {
  const [nfts, setNfts] = useState([]);
  const [owners, setOwners] = useState([]);
  const [loading, setLoading] = useState(false);
  console.log(nfts)
  
  useEffect(() => {
    const fetchRecentMint = async () => {
      const alchemy = await initSdk();
    
      // Print total NFT collection returned in the response:
      alchemy.nft
        .getOwnersForContract("0x2FECb7cC09b11763d5Ded63a33BCd384C5b6c2A9")
        .then(res => setOwners(res?.owners)); 
      alchemy.nft
        .getNftsForContract("0x2FECb7cC09b11763d5Ded63a33BCd384C5b6c2A9")
        .then(res => setNfts(res?.nfts));
    }
    fetchRecentMint();
  }, []);

  const handleMint = async () => {
    try {
      setLoading(true);
      console.log(loading);
      const { Contract } = connectContract('0x2FECb7cC09b11763d5Ded63a33BCd384C5b6c2A9', ABI);
      if (!Contract) return setLoading(false);
      console.log(Contract);
      const trx = await Contract.mint('1', {
        value: utils.parseEther('0.06'),
      });
      await trx.wait();
      setLoading(false);
    } catch {
      setLoading(false);
    }
  }

  const rows = owners?.map((item, index) => 
    <tr key={index}>
      <td>{nfts[0]?.title}</td>
      <td>{item}</td>
      <td>
        <Anchor href="https://testnets.opensea.io/assets/goerli/0x2fecb7cc09b11763d5ded63a33bcd384c5b6c2a9/0" target="_blank">
          view in opensea <IconArrowUpRight size={14} />
        </Anchor>
      </td>
    </tr>
  );

  return (
    <Container size={920}>
      <main>
        <Grid columns={24} align='center' justify='space-between'>
          <Grid.Col sm={12}>
            <Title>Indoor Compose NFT</Title>
            <Space h={24} />
            <Text>
              The environmental friendly way to reduce food waste, create nutrient-rich soil, and promote sustainable living. Become an NFT owner and digitally monitor your part of the environmental project start with 0.06 ETH.
            </Text>
            <Space h={24} /> 
            <Button px={80} size='md' loading={loading} onClick={handleMint}>Mint</Button>
          </Grid.Col>
          <Grid.Col sm={10}>
            <Image alt='' src='/Compost-Thorony2.png' width={340} height={340} />
          </Grid.Col>
        </Grid>

        <Space h={24} />
        <Title align="center">Recent Minted</Title>
        <Space h={16} />
        <Card withBorder>
          <Table>
            <thead>
              <tr>
                <th>Title</th>
                <th>Owner</th>
                <th>Opensea</th>
              </tr>
            </thead>
            <tbody>{rows}</tbody>
          </Table>
        </Card>

        <Space h={40} />
        <Grid columns={24} align='center' justify='space-between'>
          <Grid.Col sm={24}>
            <Title>One NFT = One of the Indoor Compose for every house whole</Title>
            <Space h={24} />
            <Text>
              Indoor composting is a simple and successful method of reducing waste, promoting sustainable living, and promoting a healthier environment.
              <br/>1. Reducing waste: According to the United States Environmental Protection Agency (EPA), food scraps and yard waste make up about 30% of what we throw away in the US. Indoor composting allows us to divert food waste from landfills and reduce the amount of methane gas that is generated by decomposing organic material in landfills.
              <br/><br/>2. Creating nutrient-rich soil: Composting organic material results in the creation of nutrient-rich soil that can be used to fertilize plants. This soil is often much healthier than store-bought fertilizers, which can contain harmful chemicals.
              <br/><br/>3. Supporting sustainable living: Indoor composting is a sustainable living practice that supports a circular economy. Instead of discarding food waste, it can be turned into nutrient-rich soil that can be used to grow more food, which reduces the need for chemical fertilizers and supports a more sustainable food system.
              <br/><br/>4. Saving money: Indoor composting can help save money on store-bought fertilizers and reduce waste disposal fees, especially for those living in urban areas where trash removal can be expensive.
              <br/><br/>5. Reducing greenhouse gas emissions: By composting organic material, we can reduce the amount of methane gas that is generated by decomposing waste in landfills. Methane is a potent greenhouse gas that contributes to climate change, so reducing its production is crucial for mitigating the effects of climate change.
            </Text>
          </Grid.Col>
        </Grid>

        <Space h={24} />
        <Grid columns={24} align='center' justify='space-between'>
          <Grid.Col sm={24}>
            <Title>Incentive Process, under way...</Title>
            <Space h={24} />
            <Text>
              Order a Compost Kit and send it to your decider reception.
              Connect your Matamask account to receive NFT after the completion of the purchase.
              Stake the NFT you will receive a Daily reward
              Stake your reward to get more ICK(Indoor compost Kit tokens)
              You can trade NFT in order the exchange the compost owner, you also can swap the reward you are earning from owning the compost.  
            </Text>
          </Grid.Col>
        </Grid>
      </main>
    </Container>
  );
}
